Preparations multiversion
ros-controls/control.ros.org pull request #35
Opened 2022-03-31 13:30 UTC by mamueluth

Part of : https://github.com/ros-controls/control.ros.org/issues/39
These changes are done so that the files containing the documentation are bundled and the creation of multiversion is easier.  The documentation files (*.rst) except for the index.rst are moved to the doc/ folder. Some changes in the documentation files are needed to include the moved files correctly. While moving the files, separated folders are created for each topic and images are included locally in those folders. Besides this:

- Workflow is adjusted as needed
- Readme.md is updated
- _build folder and copied/cloned ros2_contol, ros2_controllers, ros2_control_demos are excluded
- warnings for duplicated and non existing _static folder are fixed

2022-04-03 14:01 UTC, destogl requested changes
It looks good. Just a few small changes and questions.

2022-04-04 20:01 UTC, bmagyar approved these changes

2022-04-05 13:26 UTC, destogl commented on doc/resources/resources.rst
> +`Recording <https://vimeo.com/649651707/46a3be27ed>`__
```suggestion
`Recording <https://vimeo.com/649651707/46a3be27ed>`_
```

2022-04-05 13:27 UTC, destogl approved these changes

2022-04-05 13:28 UTC, merged