Add creation of a multi version documentation using sphinx-multiversion
ros-controls/control.ros.org pull request #38
Opened 2022-03-31 13:32 UTC by mamueluth

Part of : https://github.com/ros-controls/control.ros.org/issues/39
Structure is chagned as in [Preparation for multi version](https://github.com/ros-controls/control.ros.org/pull/35) . The creation of the documentation is changed to `sphinx-multiversion`. Currently, three branches are created: Foxy on foxy, galactic on galactic and rolling on master. Since the documentation for e.g. ros2_control is located in separate repositories (subrepositories) the creation of multiversion has been adjusted using scripts located in the `make_help_scripts` folder. The general idea is as follows:
1. For each branch, clone the subrepositories and checkout the branch 
2. Create temporary commits on the branch. Needed since changes in multiversion are only visible after commiting them.
3. Delete temporary commits on branches
4. Create api with doxygen and copy 

For more details, have a look at the Readme.md

2022-04-21 15:07 UTC, destogl requested changes
Just few wording corrections.

Can you please also check that CI is working again? It should execute the same command as when deployment is done, but without push to the `gh-pages` branch:

This path is missing:  `https://github.com/ros-controls/ros2_control/tree/master/transmission_interface/images`

2022-04-27 17:45 UTC, bmagyar approved these changes

2022-05-10 09:45 UTC, mamueluth commented on doc/resources/resources.rst
> +`Recording <https://vimeo.com/649651707/46a3be27ed>`__
Are you sure about this, change? I remember getting a build warning/error because of this

2022-05-10 11:21 UTC, mamueluth commented
> Just few wording corrections.
> 
> Can you please also check that CI is working again? It should execute the same command as when deployment is done, but without push to the `gh-pages` branch:
> 
> This path is missing: `https://github.com/ros-controls/ros2_control/tree/master/transmission_interface/images`

The CI should not fail after merge, when all paths are as expected and the correct conf.py is used. I checked this by merging in my own master, there foxy and galactic branches are also present. https://github.com/mamueluth/control.ros.org
The pages are built & deployed without error. https://mamueluth.github.io/control.ros.org/master/index.html

2022-05-10 11:46 UTC, destogl commented on doc/resources/resources.rst
> +`Recording <https://vimeo.com/649651707/46a3be27ed>`__
Let's keep this as it and and correct later.

2022-05-10 11:47 UTC, destogl approved these changes
Thanks for following up on the issue.

2022-05-10 15:17 UTC, merged